_target_: codis.lightning.modules.SupervisedVAE
vae:
  _target_: codis.lightning.modules.LightningBetaVAE
  img_size: ${dataset.img_size}
  latent_dim: 10
  beta: 1.0
  lr: ${training.lr}
gamma: 0.5
factors_to_regress: [orientation, scale, position_x, position_y]