name: idsprites
batch_size: 256
factor_resolution: 8
img_size: 224
num_channels: 3
num_workers: 8
shapes_per_task: 10
tasks: 310
train_split: 0.98
val_split: 0.01
test_split: 0.01
train_dataset_size: 100000
val_dataset_size: 10000
test_dataset_size: 50000