_target_: avalanche.training.supervised.EWC
optimizer:
  _target_: torch.optim.Adam
  lr: ${training.lr}
criterion:
  _target_: torch.nn.CrossEntropyLoss
mode: onlinesum
train_mb_size: ${dataset.batch_size}
eval_mb_size: ${dataset.batch_size}
train_epochs: ${trainer.max_epochs}
ewc_lambda: 0.1