_target_: avalanche.training.supervised.ICaRL
optimizer:
  _target_: torch.optim.Adam
  lr: ${training.lr}
feature_extractor:
  _target_: torchvision.models.resnet18
  weights: null
  num_classes: 256
classifier:
  _target_: torch.nn.Linear
  in_features: 256
  out_features: ${eval:'${dataset.tasks} * ${dataset.shapes_per_task}'}
fixed_memory: true
train_mb_size: ${dataset.batch_size}
eval_mb_size: ${dataset.batch_size}
train_epochs: ${trainer.max_epochs}
memory_size: 2000